Spring:
  application:
    name: "rvps-revuePorteFeuille"
  datasource:
    ## INT
    ##driver-class-name: com.ibm.db2.jcc.DB2Driver
    #url: jdbc:db2://O4DREVAL-DB2-INTG.azfr.allianz:50008/O4DREVAL
    #username: O42WEBM
    #password: V5W%qU8/pBF4!unGER!-
    ## mysql
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://167.86.84.94:3309/betguilde
    #username: root
    #password: root
    # Configuration de la base de données H2
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

    schema: classpath:data.sqlV0


    # Chemin du script SQL pour créer la table
    # Activation de la console H2 (optionnel, pour accéder à la console H2)
    h2:
      console:
        enabled: true
        path: h2-console





  banner:
    location: banner.txt
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql : true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true



  sql:
    init:
      schema-locations:
        classpath: create_table.sql



